### ISSUE TITLE
[data quality] npm/nyc v11.4.1

### ISSUE THREAD

**Issue by noqcks** [google/deps.dev#36]
I noticed some odd dependency versionKy names seemingly only on version `11.4.1` of the npm package `nyc` with `>` symbols

https://api.deps.dev/v3alpha/systems/npm/packages/nyc/versions/11.4.1:dependencies

```
versionKey": {
  "system": "NPM",
  "name": "nyc>11.4.1>align-text",
  "version": "0.1.4"
},
```

later versions of nyc such a 15.1.0 have normal versionKey names 
https://api.deps.dev/v3alpha/systems/npm/packages/nyc/versions/15.1.0:dependencies
```
versionKey": {
  "system": "NPM",
  "name": "color-convert",
  "version": "2.0.1"
},
```

**Comment by noqcks** [comment]
Also noticed it on browser-launcher 0.3.5 https://api.deps.dev/v3alpha/systems/npm/packages/browser-launcher/versions/0.3.5:dependencies

**Comment by adg** [comment]
This is because these dependencies are "[bundled](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#bundledependencies)", and the name in this case `"nyc>11.4.1>align-text"` specifies the version (`nyc` version `11.4.1`) that is bundling package `align-text`. 

Note that the `bundled` field of the node object is set to `true`:
```
    {
      "versionKey": {
        "system": "NPM",
        "name": "nyc>11.4.1>align-text",
        "version": "0.1.4"
      },
      "bundled": true,
      "relation": "INDIRECT",
      "errors": []
    },
```

This is documented by the [`GetDependencies`](https://docs.deps.dev/api/v3alpha/#getdependencies) endpoint docs.
