### ISSUE TITLE
Add dependent counts to the API

### ISSUE THREAD

**Issue by mudongliang** [google/deps.dev#95]
Hi there,

we are trying to use deps.dev free API to replace bigquery in the criticality_score. The GCP configuration is not easy to use.

However, the current API only provides the dependency packages `a specified package A` depends on, other than the dependents which depends on `the specified package A`. So if we can collect the dependency graphs for all packages from deps.dev, we can calculate the count of dependents which depends on `a specified package A`.

Please correct us if we make any misunderstanding. Or if there is any convenience way to retrieve the dependents count.

**Comment by sarnesjo-google** [comment]
Hi @mudongliang! Dependent counts are not currently available from the API, but I'll take this feature request to the team. Please let me know if I've misunderstood your request.

Do note that we can't make the API return actual list of dependents, as it can be very large (100k+). For that you would still need to use the BigQuery dataset.

**Comment by mudongliang** [comment]
I see. Thanks very much.

**Comment by sarnesjo-google** [comment]
Hi again! There is now a [GetDependents](https://docs.deps.dev/api/v3alpha/#getdependents) endpoint in the v3alpha API, which serves the same dependent counts as the deps.dev website. Please take a look and let us know if you have any questions or spot any issues.

**Comment by mudongliang** [comment]
Thanks, I will check it ASAP.

**Comment by mudongliang** [comment]
I have several questions about this API result.

- I checked the react package, [its office webpage](https://www.npmjs.com/package/react?activeTab=dependents) shows 226195 dependents, meanwhile, [the API result](https://api.deps.dev/v3alpha/systems/npm/packages/react/versions/18.3.1:dependents) shows 303716 dependents.
- From the API result, the total dependentCount != directDependentCount + indirectDependentCount. See below

{"dependentCount":303716, "directDependentCount":148783, "indirectDependentCount":156509}

**Comment by sarnesjo-google** [comment]
> I checked the react package, [its office webpage](https://www.npmjs.com/package/react?activeTab=dependents) shows 226195 dependents, meanwhile, [the API result](https://api.deps.dev/v3alpha/systems/npm/packages/react/versions/18.3.1:dependents) shows 303716 dependents.

The dependent counts served by deps.dev are derived from the dependency graphs computed by deps.dev. They differ from the counts produced by npmjs.com in a few ways:

- deps.dev computes how many dependents each _version_ has (with the caveat that this is based on computed dependency graphs). Best I can tell, npmjs.com computes dependents per package (note that [15.0.0](https://www.npmjs.com/package/react/v/15.0.0?activeTab=dependents) and [16.0.0](https://www.npmjs.com/package/react/v/16.0.0?activeTab=dependents) shows the same number of dependents).
- deps.dev counts direct and indirect dependents. As far as I know, npmjs.com counts only direct dependents.

Please note that neither the dependent counts served by deps.dev nor by npmjs.com is the "actual" number of dependents, as neither count includes non-public usage. As mentioned in the [documentation](https://docs.deps.dev/api/v3alpha/#getdependents), dependent counts should be treated as indicative of relative popularity rather than precisely accurate.

> From the API result, the total dependentCount != directDependentCount + indirectDependentCount.

As mentioned in the [documentation](https://docs.deps.dev/api/v3alpha/#getdependents), the total dependent count may be less than the sum of the direct and indirect dependent counts. The reason for this is that some dependents are both direct and indirect.

**Comment by mudongliang** [comment]
Thanks for your kind explanation. My problems are all solved.
